# -*- coding: utf-8 -*-
"""QC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWqpTwlDgWfs-y0AN2Ckguo8iH27SeYj
"""

!pip install qiskit

pip install pylatexenc

import qiskit
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit, assemble, transpile, QuantumRegister, ClassicalRegister
from qiskit.tools.visualization import circuit_drawer
from qiskit.providers.aer import QasmSimulator
from qiskit.visualization import plot_histogram

circuit = QuantumCircuit(2, 2)
circuit.h(0)
circuit.cx(0, 1)
circuit.measure([0,1], [0,1])
circuit.draw()

simulator = QasmSimulator()
transpiled = transpile(circuit, simulator)
job = simulator.run(transpiled, shot=8192)
result = job.result()
counts = result.get_counts()
plot_histogram(counts, title = "Bell state")

"""Read NC Chapter 1

"""

